# Generated by Django 5.0.7 on 2026-09-27 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_remove_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(default='1', max_length=128),
        ),
        migrations.AlterField(
            model_name='customer',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
